from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
REPO_ROOT = PROJECT_ROOT.parent

DEFAULT_BENCHMARK_PATH = REPO_ROOT / "DSPy_Multihop_QA.json"
DEFAULT_SOURCE_DIR = REPO_ROOT / "dspy"
DEFAULT_RESULTS_DIR = PROJECT_ROOT / "results"

DEFAULT_REACT_MAX_ITERS = 6
DEFAULT_TOOL_CHAR_LIMIT = 3000
DEFAULT_TOOL_MAX_MATCHES = 12
DEFAULT_TOOL_MAX_READ_LINES = 120
DEFAULT_TOOL_TIMEOUT_SECONDS = 15
